"""add mathscinet_id and math_genealogy_url

Revision ID: 461aa95cff5f
Revises: 69c90f7109df
Create Date: 2026-09-14 06:30:39.325029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461aa95cff5f'
down_revision = '69c90f7109df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mathscinet_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('math_genealogy_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researchers', schema=None) as batch_op:
        batch_op.drop_column('math_genealogy_url')
        batch_op.drop_column('mathscinet_id')

    # ### end Alembic commands ###
