"""Initial schema

Revision ID: 688993557a87
Revises: 
Create Date: 2026-09-12 07:32:41.385914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688993557a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researchers',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('affiliation', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phd_institute', sa.String(length=255), nullable=True),
    sa.Column('phd_year', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('orcid', sa.String(length=50), nullable=True),
    sa.Column('arxiv_id', sa.String(length=50), nullable=True),
    sa.Column('google_scholar_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('researchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_researchers_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_researchers_slug'), ['slug'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('researcher_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('researcher_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_researcher_emails_email'), ['email'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('researcher_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('collaborations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('researcher_a_id', sa.String(length=36), nullable=False),
    sa.Column('researcher_b_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('ESTABLISHED', 'ONGOING', name='collaborationstatus'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('researcher_a_id < researcher_b_id', name='check_undirected_edge'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['researcher_a_id'], ['researchers.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['researcher_b_id'], ['researchers.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('researcher_a_id', 'researcher_b_id', name='uq_collaboration_edge')
    )
    with op.batch_alter_table('collaborations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collaborations_researcher_a_id'), ['researcher_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaborations_researcher_b_id'), ['researcher_b_id'], unique=False)

    op.create_table('researcher_correction_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.String(length=36), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('researcher_correction_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_researcher_correction_reports_researcher_id'), ['researcher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_researcher_correction_reports_status'), ['status'], unique=False)

    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('collaboration_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaboration_id', sa.String(length=36), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collaboration_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collaboration_reports_collaboration_id'), ['collaboration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_reports_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaboration_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collaboration_reports_status'))
        batch_op.drop_index(batch_op.f('ix_collaboration_reports_collaboration_id'))

    op.drop_table('collaboration_reports')
    op.drop_table('user_role')
    with op.batch_alter_table('researcher_correction_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_researcher_correction_reports_status'))
        batch_op.drop_index(batch_op.f('ix_researcher_correction_reports_researcher_id'))

    op.drop_table('researcher_correction_reports')
    with op.batch_alter_table('collaborations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collaborations_researcher_b_id'))
        batch_op.drop_index(batch_op.f('ix_collaborations_researcher_a_id'))

    op.drop_table('collaborations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('researcher_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_researcher_emails_email'))

    op.drop_table('researcher_emails')
    op.drop_table('roles')
    with op.batch_alter_table('researchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_researchers_slug'))
        batch_op.drop_index(batch_op.f('ix_researchers_display_name'))

    op.drop_table('researchers')
    # ### end Alembic commands ###
