"""add research_interests

Revision ID: 69c90f7109df
Revises: 688993557a87
Create Date: 2026-09-13 14:47:46.890498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c90f7109df'
down_revision = '688993557a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('research_interests', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researchers', schema=None) as batch_op:
        batch_op.drop_column('research_interests')

    # ### end Alembic commands ###
